#!/bin/bash

source ${1:-inventory}

JOB_LIST_URL="$JENKINS_BASE/api/json?pretty=true"
JOBS=$(wget --quiet -O - $JOB_LIST_URL --auth-no-challenge --no-check-certificate --http-user=$USER --http-password=$API_TOKEN | egrep -o 'http[s]?://.*/job/[^"]*' | rev | cut -d / -f2 | rev )

for job in $JOBS
do
    echo $job
    url=$JENKINS_BASE/job/$job/config.xml?token=$API_TOKEN
    wget --quiet -O $job.config --auth-no-challenge --no-check-certificate --http-user=$USER --http-password=$API_TOKEN $url
done
